# 23. Write a program to input eight numbers from the user and display all the unique 
# numbers (once). 
set = set()
a1 = (input("Enter num: "))
set.add(int(a1))
a2 = (input("Enter num: "))
set.add(int(a2))
a3 = (input("Enter num: "))
set.add(int(a3))
a4 = (input("Enter num: "))
set.add(int(a4))
a5 = (input("Enter num: "))
set.add(int(a5))
a6 = (input("Enter num: "))
set.add(int(a6))
a7 = (input("Enter num: "))
set.add(int(a7))
a8 = (input("Enter num: "))
set.add(int(a8))
print(set)